global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:3007"]

  - job_name: "node-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "motus-leaderbord-1"
    scrape_interval: 30s
    metrics_path: /api/metrics
    static_configs:
      - targets: ["motus-gateway-1:3000"]

  - job_name: "motus-leaderbord-2"
    scrape_interval: 30s
    metrics_path: /api/metrics
    static_configs:
      - targets: ["motus-gateway-2:3000"]
